x-app: &app
    image: agroportal/ontologies_api:development
    environment: &env
      BUNDLE_PATH: /srv/ontoportal/bundle
      # default bundle config resolves to /usr/local/bundle/config inside of the container
      # we are setting it to local app directory if we need to use 'bundle config local'
      BUNDLE_APP_CONFIG: /srv/ontoportal/ontologies_api/.bundle
      COVERAGE: 'true'
      GOO_REDIS_HOST: redis-ut
      REDIS_GOO_CACHE_HOST: redis-ut
      REDIS_HTTP_CACHE_HOST: redis-ut
      REDIS_PERSISTENT_HOST: redis-ut
      REDIS_HOST: redis-ut
      REDIS_PORT: 6379
      SOLR_HOST: solr-ut
      SOLR_TERM_SEARCH_URL: http://solr-ut:8983/solr/term_search_core1
      SOLR_PROP_SEARCH_URL: http://solr-ut:8983/solr/prop_search_core1
      MGREP_HOST: mgrep-ut
      MGREP_PORT: 55555
    stdin_open: true
    tty: true
    command: "bundle exec rackup -o 0.0.0.0 --port 9393"
    ports:
      - 9393:9393
    volumes:
      # bundle volume for hosting gems installed by bundle; it helps in local development with gem udpates
      - bundle:/srv/ontoportal/bundle
      # api code
      - app_api:/srv/ontoportal/ontologies_api
      # mount directory containing development version of the gems if you need to use 'bundle config local'
      #- /Users/alexskr/ontoportal:/Users/alexskr/ontoportal
    depends_on:
      - solr-ut
      - redis-ut
      - mgrep-ut


x-app: &default-app
  #image: agroportal/ontoportal_web_ui:test
  image: imadpyth/bioportal_web_ui:development
  env_file:
    .env_ui
  tty: true
  volumes:
    - app_web:/app
    - bundle:/usr/local/bundle
    - node:/node_modules
    - rails_cache:/app/tmp/cache
    - assets:/app/public/assets
    - /var/run/docker.sock:/var/run/docker.sock
  tmpfs:
    - /tmp
    - /app/tmp/pids


services:
  api:
    <<: *app
    env_file:
      .env_api
    environment:
      <<: *env
      GOO_BACKEND_NAME: 4store
      GOO_PORT: 9000
      GOO_HOST: 4store-ut
      GOO_PATH_QUERY: /sparql/
      GOO_PATH_DATA: /data/
      GOO_PATH_UPDATE: /update/
    profiles:
      - 4store
    depends_on:
      - solr-ut
      - redis-ut
      - mgrep-ut
      - 4store-ut

  redis-ut:
    image: redis
    ports:
      - 6379:6379

  4store-ut:
    image: bde2020/4store
    #volume: fourstore:/var/lib/4store
    ports:
      - 9000:9000
    command: >
      bash -c "4s-backend-setup --segments 4 ontoportal_kb
      && 4s-backend ontoportal_kb
      && 4s-httpd -D -s-1 -p 9000 ontoportal_kb"
    profiles:
      - 4store

  solr-ut:
    image: solr:8
    volumes:
      - ./ontologies_linked_data/test/solr/configsets/:/configsets:ro
      #- ./test/solr/configsets:/configsets:ro
    ports:
      - "8983:8983"
    command: >
      bash -c "precreate-core term_search_core1 /configsets/term_search
      && precreate-core prop_search_core1 /configsets/property_search
      && solr-foreground"

  mgrep-ut:
    image: ontoportal/mgrep-ncbo:0.1
    ports:
      - "55556:55555"



# UI services
  
  db:
    image: "mysql:8.0"
    networks:
      - default
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 100  

  cache:
    image: memcached:latest
    restart: unless-stopped
    command: [ "-m", "1024" ]
    networks:
      - default
    ports:
      - "11211:11211"
  node:
    <<: *default-app
    command: "yarn build --watch"

  rails:
    <<: *default-app
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      node:
        condition: service_started
    links:
      - db
      - cache
    environment:
      BUNDLE_WITHOUT: ''
      DB_HOST: db
      CACHE_HOST: cache
    ports:
      - "3000:3000"

  test:
    <<: *default-app
    depends_on:
      - db
      - cache
      - chrome-server
    network_mode: 'host'
    environment:
      BUNDLE_WITHOUT: ''
      DB_HOST: 127.0.0.1
      CACHE_HOST: 127.0.0.1
  chrome-server:
    image: selenium/standalone-chrome:112.0-chromedriver-112.0-grid-4.9.0-20230421
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
volumes:
  bundle:
  app_api:
  app_web:

  mysql-data:
  bundle:
  rails_cache:
  assets:
  node:
  #fourstore:
