# name: ontoportal-agraph

x-app: &api
  stdin_open: true
  tty: true
  environment: &env
    GOO_BACKEND_NAME: ag
    GOO_PORT: 10035
    GOO_HOST: agraph
    GOO_PATH_QUERY: /repositories/ontoportal
    GOO_PATH_DATA: /repositories/ontoportal/statements
    GOO_PATH_UPDATE: /repositories/ontoportal/statements
  depends_on: &depends_on
    solr-term:
      condition: service_healthy
    solr-prop:
      condition: service_healthy
    redis-persistent:
      condition: service_healthy
    redis-goo-cache:
      condition: service_healthy
    redis-http-cache:
      condition: service_healthy
    mgrep:
      condition: service_started
    agraph:
      condition: service_started

services:
  api:
    <<: *api

  ncbo_cron:
    <<: *api

  agraph:
    image: franzinc/agraph:v7.4.0.t3
    platform: linux/amd64
    environment:
      - AGRAPH_SUPER_USER=test
      - AGRAPH_SUPER_PASSWORD=xyzzy
    shm_size: 1g
    volumes:
      - ag_data:/agraph/data
    ports:
      - 10035:10035
