# docker compose file for spinning up backend services with ports mapped to local host
# This is useful for running api on local system (outside of docker container) while accessing
# dockerised backend services

services:

  redis:
    image: redis
    ports:
      - 6379:6379

  4store:
    image: bde2020/4store
    platform: linux/amd64
    #volume: fourstore:/var/lib/4store
    command: >
      bash -c "4s-backend-setup --segments 4 ontoportal_kb
      && 4s-backend ontoportal_kb
      && 4s-httpd -D -s-1 -p 9000 ontoportal_kb"
    ports:
      - 9000:9000


  solr:
    image: ontoportal/solr-ut:0.0.2
    ports:
      - 8983:8983

  mgrep:
    image: ontoportal/mgrep:0.0.2
    platform: linux/amd64
    # volumes:
    #  - mgrep:/srv/mgrep/dictionary
    ports:
      - 55556:55556 #port 55555 is not avaiable on mac so you need to choose another port and update .env

  agraph:
    image: franzinc/agraph:v7.4.0.t3
    platform: linux/amd64
    environment:
      - AGRAPH_SUPER_USER=test
      - AGRAPH_SUPER_PASSWORD=xyzzy
    shm_size: 1g
    ports:
      - 10035:10035
    command: >
       bash -c "/agraph/bin/agraph-control --config /agraph/etc/agraph.cfg start
       ; agtool repos create bioportal_test
       ; agtool users add anonymous
       ; agtool users grant anonymous root:bioportal_test:rw
       ; tail -f /agraph/data/agraph.log"
    profiles:
      - agraph

volumes:
  bundle:
 #fourstore:
