x-app: &api
  stdin_open: true
  tty: true
  env_file:
    .env
  depends_on: &depends_on
    solr:
      condition: service_started
    redis:
      condition: service_healthy
    mgrep:
      condition: service_started
    4store:
      condition: service_started

services:
  api:
    <<: *api
    image: ${IMAGE_REPOSITORY}/ontologies_api:${IMAGE_TAG}
    command: "bundle exec rackup -o 0.0.0.0 --port 9393"
    env_file:
      .env
    volumes:
      - history:/usr/local/hist
      - repository:/srv/ontoportal/data/repository
      - reports:/srv/ontoportal/data/reports
    ports:
      - 9393:9393

  ncbo_cron:
    <<: *api
    image: ${IMAGE_REPOSITORY}/ncbo_cron:${IMAGE_TAG}
    command: "bundle exec bin/ncbo_cron"
    volumes:
      - history:/usr/local/hist
      - repository:/srv/ontoportal/data/repository
      - reports:/srv/ontoportal/data/reports
      - mgrep:/srv/ontoportal/data/mgrep
      - logs:/srv/ontoportal/ncbo_cron/logs

  redis:
    image: redis
    command: ["redis-server", "--save", "", "--maxmemory-policy", "volatile-ttl", "--maxmemory", "128000000"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 10

  4store:
    image: bde2020/4store
    platform: linux/amd64
    volumes:
     - 4store_data:/var/lib/4store
    command: bash -c "4s-backend ontoportal_kb && 4s-httpd -D -s-1 -p 9000 ontoportal_kb"

  solr:
    image: solr:9.1
    command: bin/solr start -cloud -f

  mgrep:
    image: ontoportal/mgrep:0.0.2
    platform: linux/amd64
    volumes:
      - mgrep:/srv/mgrep/dictionary
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "localhost", "55556"]
      start_period: 3s
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  bundle:
  4store_data:
  ag_data:
  repository:
  mgrep:
  reports:
  redis_data:
  history:
  logs:
  solr_data:
